export const apiTypes = {
  FETCH_STATS: 'FETCH_STATS',
  SEND_FOR_ANALYSIS: 'SEND_FOR_ANALYSIS',
  SEND_FEEDBACK: 'SEND_FEEDBACK'
};

export const dataTypes = {
  SET_IMAGE: 'SET_IMAGE',
  SET_CONSET_GIVEN: 'SET_CONSET_GIVEN',
  RESET_DATA: 'RESET_DATA',
  SET_IMAGE_INPUT_MODE: 'SET_IMAGE_INPUT_MODE'
};

export const helperTypes = {
  SET_SHOW_ORIENTATION_MSG: 'SET_SHOW_ORIENTATION_MSG'
};
